name: build

on: push

jobs:
  my-job:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.21
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Golang CGO cross compiler dynamic link library
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: resolve-metadata
          targets: windows/amd64,darwin/amd64,darwin/arm64
          v: false
          x: false
          race: false
          ldflags: -s -w
          buildmode: c-shared

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/resolve-metadata*
